export default [
    { path: '/dashboard', component: require('./components/Dashboard.vue').default },
    { path: '/profile', component: require('./components/Profile.vue').default },
    { path: '/developer', component: require('./components/Developer.vue').default },
    { path: '/users', component: require('./components/Users.vue').default },
    { path: '/products', component: require('./components/product/Products.vue').default },
    { path: '/product/tag', component: require('./components/product/Tag.vue').default },
    { path: '/product/category', component: require('./components/product/Category.vue').default },
    { path: '*', component: require('./components/NotFound.vue').default },
    { path: '/instituciones', component: require('./components/Instituciones.vue').default },
    { path: '/instituciones/confirmar', component: require('./components/ConfirmarInstituciones.vue').default },
    { path: '/bibliotecas', component: require('./components/Bibliotecas.vue').default },
    { path: '/bibliotecas/registro', component: require('./components/registroBiblioteca.vue').default },
    { path: '/bibliotecas/confirmar', component: require('./components/confirmarBibliotecas.vue').default },
    { path: '/alumnos', component: require('./components/Alumnos.vue').default },
    { path: '/profesores', component: require('./components/Profesores.vue').default },
    { path: '/personal', component: require('./components/Personal.vue').default },
    { path: '/prestamos', component: require('./components/Prestamos.vue').default },
    { path: '/prestamos/solicitar', component: require('./components/SolicitarPrestamo.vue').default },
    { path: '/prestamos/estado', component: require('./components/EstadoPrestamos.vue').default },
    { path: '/prestamos/buscar', component: require('./components/Busqueda.vue').default },
    { path: '/libros', component: require('./components/Libros.vue').default },
    { path: '/libros/registrar', component: require('./components/registrarLibro.vue').default },
    { path: '/libros/confirmar', component: require('./components/confirmarRegistros.vue').default },
    { path: '/copias', component: require('./components/Copias.vue').default },
    { path: '/copias/registrar', component: require('./components/RegistrarCopia.vue').default },
    { path: '/copias/confirmar', component: require('./components/confirmarCopia.vue').default },
    { path: '/autores', component: require('./components/Autores.vue').default},
    { path: '/editoriales', component: require('./components/Editoriales.vue').default},

];